name: webserver-snp
version: 0.0.1.0
license: MIT
author: "Alexander Kobjolke"
maintainer: "alex@jakalx.net"
copyright: "Alexander Kobjolke 2022"

extra-source-files:
  - README.org

dependencies:
  - aeson ^>= 2.0
  - ascii ^>= 1.2.3.0
  - async ^>= 2.2.2
  - attoparsec ^>= 0.13 || ^>= 0.14
  - base ^>= 4.14 || ^>= 4.15 || ^>= 4.16
  - blaze-html ^>= 0.9
  - bytestring ^>= 0.10 || ^>= 0.11
  - containers ^>= 0.6.2.1
  - directory ^>= 1.3.6
  - filepath ^>= 1.4
  - list-transformer ^>= 1.0.7
  - network ^>= 3.1.2
  - network-simple ^>= 0.4.2
  - relude ^>= 1.0 || ^>= 1.1
  - resourcet ^>= 1.2.4
  - safe-exceptions ^>= 0.1.7.0
  - stm ^>= 2.5
  - text ^>= 1.2.4.1
  - time
  - unfork ^>= 1.0

ghc-options:
  - -Wall
  - -Wunused-packages
  - -fdefer-typed-holes

language: GHC2021
default-extensions:
  - GHC2021
  - BlockArguments

library:
  source-dirs: src

executables:
  snp-server:
    source-dirs: app
    main: webserver.hs
    dependencies:
      - webserver-snp

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - webserver-snp
      - hspec
      - QuickCheck
    build-tools: hspec-discover
